security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: plaintext
    providers:
        in_memory:
            memory:
                users:
                    jolicode: { password: ouiiiiiiiiiiiiiiiiii }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        home:
            pattern: ^/$
            http_basic: true

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
