security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    jolicode: { password: ouiiiiiiiiiiiiiiiiii }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        home:
            pattern: ^/$
            anonymous: false
            http_basic: true

    access_control:
