parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        http_client:
            class: Symfony\Component\HttpClient\MockHttpClient
